
$(document).ready(function(){
    $('.teacher-check').hide();
    $('.feedback-modal-view').hide();
    $('.send-email').hide();
    $('#loading').hide();
    $(window).on('load',function(){
        $('.preloader').fadeOut(1000);
        $(".wrapper").css("visibility", "visible");
        $('body').css('overflow-x','');
        $('.wrapper').fadeIn(1000);
    })
    $('.side-1').show();
    $('.side-2').hide();
    $('.side-3').hide();
    $('.side-4').hide();
    $('.side-5').hide();
    $('.side-6').hide();
    $('.side-7').hide();
    $(document).on('click','.dash',function(){
        $('.side-1').show();
        $('.side-2').hide();
        $('.side-3').hide();
        $('.side-4').hide();
        $('.side-5').hide();
        $('.side-6').hide();
        $('.side-7').hide();
    });
    $(document).on('click','.teacher',function(){
        $('.nav-item').removeClass('active');
        $(this).addClass('active');
        $('.side-2').show();
        $('.side-1').hide();
        $('.side-3').hide();
        $('.side-4').hide();
        $('.side-5').hide();
        $('.side-6').hide();
        $('.side-7').hide();
        

    });
    $(document).on('click','.student',function(){
        $('.side-3').show();
        $('.side-1').hide();
        $('.side-2').hide();
        $('.side-4').hide();
        $('.side-5').hide();
        $('.side-6').hide();
        $('.side-7').hide();
        $('.nav-item').removeClass('active');
        $(this).addClass('active');
    });
    $(document).on('click','.status',function(){
        $('.side-4').show();
        $('.side-1').hide();
        $('.side-2').hide();
        $('.side-3').hide();
        $('.side-5').hide();
        $('.side-6').hide();
        $('.side-7').hide();
        $('.nav-item').removeClass('active');
        $(this).addClass('active');
    });
    $(document).on('click','.add-teacher',function(){
        $('.side-5').show();
        $('.side-1').hide();
        $('.side-2').hide();
        $('.side-3').hide();
        $('.side-4').hide();
        $('.side-6').hide();
        $('.side-7').hide();
        $('.nav-item').removeClass('active');
        $(this).addClass('active');
    });
    $(document).on('click','.feedback',function(){
        $('.side-6').show();
        $('.side-1').hide();
        $('.side-2').hide();
        $('.side-3').hide();
        $('.side-4').hide();
        $('.side-5').hide();
        $('.side-7').hide();
        $('.nav-item').removeClass('active');
        $(this).addClass('active');
    });
    $(document).on('click','.contact',function(){
        $('.side-7').show();
        $('.side-1').hide();
        $('.side-2').hide();
        $('.side-3').hide();
        $('.side-4').hide();
        $('.side-5').hide();
        $('.side-6').hide();
        $('.nav-item').removeClass('active');
        $(this).addClass('active');
    });
});